project:
  type: website

website:
  title: "Gabriel Sotomayor López"
  site-url: "https://gabrielsotomayorl.github.io"
  repo-url:  https://github.com/GabrielSotomayorl/GabrielSotomayorl.github.io
  description: "Sociólogo, profesor en la Universidad Diego Portales y Analista de Investigación Social (MDSF)."
  navbar:
    left:
      - text: "Sobre mí"
        href: index.qmd
      - text: "Docencia"
        href: docencia/index.qmd
      - text: "Publicaciones"
        href: publicaciones/index.qmd
      - text: "Proyectos"
        href: proyectos/index.qmd
    right:
      - icon: envelope
        href: "mailto:gabrielsotomayorl@gmail.com"
      - icon: github
        href: https://github.com/GabrielSotomayorl
      - icon: linkedin
        href: https://www.linkedin.com/in/gabriel-sotomayor/
  search: true
  page-footer:
    left: 'Hecho con [Quarto](https://quarto.org)'

format:
  html:
    theme:
      # Misma base en ambos modos → composición idéntica
      light: [cosmo, styles-light.scss]
      dark:  [cosmo, styles-dark.scss]
    toc: true
    respect-user-color-scheme: true
    lang: es
    include-in-header: google-search-console.html

execute:
  freeze: auto

